/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { registerInput, loginInput } from "../auth/auth.schema.js";
import { listParksInput, byIdInput, createParkInput, updateParkInput } from "../parks/parks.schema.js";
import type { AuthRouter } from "../auth/auth.router.js";
import type { ParksRouter } from "../parks/parks.router.js";
import type { RegionsRouter } from "../regions/regions.router.js";

const appRouter = t.router({
  auth: t.router({
    register: publicProcedure
      .input(registerInput)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<AuthRouter["register"]>>),
    login: publicProcedure
      .input(loginInput)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<AuthRouter["login"]>>),
    me: publicProcedure
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<AuthRouter["me"]>>)
    }),
  health: t.router({
    check: publicProcedure
      .output(z.object({
  status: z.string(),
}))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  parks: t.router({
    list: publicProcedure
      .input(listParksInput)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<ParksRouter["list"]>>),
    byId: publicProcedure
      .input(byIdInput)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<ParksRouter["byId"]>>),
    create: publicProcedure
      .input(createParkInput)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<ParksRouter["create"]>>),
    update: publicProcedure
      .input(updateParkInput)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<ParksRouter["update"]>>),
    delete: publicProcedure
      .input(byIdInput)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<ParksRouter["delete"]>>)
    }),
  regions: t.router({
    list: publicProcedure
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<RegionsRouter["list"]>>),
    citiesByRegion: publicProcedure
      .input(z.object({
  regionId: z.number(),
}))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<RegionsRouter["citiesByRegion"]>>)
    })
});

export type AppRouter = typeof appRouter;
